HOSTS:
  master01:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_memsize: 1024
  node01:
    roles:
      - node
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  node02:
    roles:
      - node
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  node03:
    roles:
      - node
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 512
  synced_folder: disabled
# vb_gui: true
